pub mod prelude {
    pub use super::adicional::Entity as Adicional;
    pub use super::avaliacao_loja::Entity as AvaliacaoLoja;
    pub use super::avaliacao_produto::Entity as AvaliacaoProduto;
    pub use super::categoria_produtos::Entity as CategoriaProdutos;
    pub use super::cliente::Entity as Cliente;
    pub use super::configuracoes_pedidos_loja::Entity as ConfiguracoesPedidosLoja;
    pub use super::endereco_entrega::Entity as EnderecoEntrega;
    pub use super::endereco_loja::Entity as EnderecoLoja;
    pub use super::endereco_usuario::Entity as EnderecoUsuario;
    pub use super::entregador::Entity as Entregador;
    pub use super::funcionario::Entity as Funcionario;
    pub use super::horarios_funcionamento::Entity as HorariosFuncionamento;
    pub use super::ingrediente::Entity as Ingrediente;
    pub use super::item_pedido::Entity as ItemPedido;
    pub use super::loja::Entity as Loja;
    pub use super::loja_favorita::Entity as LojaFavorita;
    pub use super::partes_item_pedido::Entity as PartesItemPedido;
    pub use super::pedido::Entity as Pedido;
    pub use super::produto::Entity as Produto;
    pub use super::promocao::Entity as Promocao;
    pub use super::cupom::Entity as Cupom;
    pub use super::uso_cupom::Entity as UsoCupom;
    pub use super::usuario::Entity as Usuario;
}

pub mod adicional;
pub mod avaliacao_loja;
pub mod avaliacao_produto;
pub mod categoria_produtos;
pub mod cliente;
pub mod configuracoes_pedidos_loja;
pub mod endereco_entrega;
pub mod endereco_loja;
pub mod endereco_usuario;
pub mod entregador;
pub mod funcionario;
pub mod horarios_funcionamento;
pub mod ingrediente;
pub mod item_pedido;
pub mod loja;
pub mod loja_favorita;
pub mod partes_item_pedido;
pub mod pedido;
pub mod produto;
pub mod promocao;
pub mod cupom;
pub mod uso_cupom;
pub mod usuario;
