pub mod repository;
pub mod storage;
pub mod usuario_port;
pub mod loja_port;
pub mod pedido_port;
pub mod produto_port;
pub mod categoria_port;
pub mod adicional_port;
pub mod cupom_port;
pub mod promocao_port;
pub mod endereco_entrega_port;
pub mod endereco_usuario_port;
pub mod endereco_loja_port;
pub mod avaliacao_loja_port;
pub mod avaliacao_produto_port;
pub mod config_pedido_port;
pub mod horario_port;
pub mod funcionario_port;
pub mod entregador_port;
pub mod cliente_port;
pub mod ingrediente_port;
pub mod loja_favorita_port;
pub mod to_proto;

// Re-export all traits and types
pub use repository::{RepositoryPort, Entity};
pub use storage::ImageStoragePort;
pub use usuario_port::UsuarioRepositoryPort;
pub use loja_port::LojaRepositoryPort;
pub use pedido_port::{PedidoRepositoryPort, PedidoComEntrega, PedidoComEntregador};
pub use produto_port::ProdutoRepositoryPort;
pub use categoria_port::CategoriaRepositoryPort;
pub use adicional_port::AdicionalRepositoryPort;
pub use cupom_port::CupomRepositoryPort;
pub use promocao_port::PromocaoRepositoryPort;
pub use endereco_entrega_port::EnderecoEntregaRepositoryPort;
pub use endereco_usuario_port::EnderecoUsuarioRepositoryPort;
pub use endereco_loja_port::EnderecoLojaRepositoryPort;
pub use avaliacao_loja_port::AvaliacaoDeLojaRepositoryPort;
pub use avaliacao_produto_port::AvaliacaoDeProdutoRepositoryPort;
pub use config_pedido_port::ConfiguracaoPedidosLojaRepositoryPort;
pub use horario_port::HorarioFuncionamentoRepositoryPort;
pub use funcionario_port::FuncionarioRepositoryPort;
pub use entregador_port::EntregadorRepositoryPort;
pub use cliente_port::ClienteRepositoryPort;
pub use ingrediente_port::IngredienteRepositoryPort;
pub use loja_favorita_port::LojaFavoritaRepositoryPort;
